### ISSUE TITLE
problem in dropper 

### ISSUE THREAD

**Issue by Zer0x3a** [D4Vinci/Dr0p1t-Framework#19]
![19832712_1918502855058770_236649782_n](https://user-images.githubusercontent.com/29900800/27841296-0b2c7018-60ce-11e7-843b-b7b72a88f69b.png)

I created a new server from metasploit , but i face the previous problem as in a picture . 

----------------
![default](https://user-images.githubusercontent.com/29900800/27841321-4558c476-60ce-11e7-97df-b474613c7bb1.PNG)
what is the problem ?

**Comment by Zer0x3a** [comment]
![2222](https://user-images.githubusercontent.com/29900800/27841373-86d1004e-60ce-11e7-8ffa-4137afaa4aa0.PNG)

**Comment by tugdualnicolas** [comment]
Give a look a other issue before create another one.

**Comment by D4Vinci** [comment]
- This error reported before many times so tell what's the output of this command?
`wine /root/.wine/drive_c/Python27/python.exe /root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py`

- Try doing this commands:
`sudo wine /root/.wine/drive_c/Python27/python.exe -m pip install --upgrade pip
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip uninstall pyinstaller
sudo wine /root/.wine/drive_c/Python27/python.exe -m pip install pyinstaller`

**Comment by Zer0x3a** [comment]
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'

**Comment by hostbob** [comment]
hey bro, i understand to build a project ain't an easy task. but why don't you try get Kali linux as some users who are gonna be using your project will be trying on there. this command you said to be tried on Kali gives error like python.exe won't be recognize by Kali. On my own i have uninstall and reinstaller pyinstaller and i even copy code in pyinstaller-script.py from windows to Kali yet still got error. maybe if you try Kali linux enviroment you might easily fix the error because i have tried many times but still not getting it working even compile with --nocompile command and try using py2exe still got error

**Comment by D4Vinci** [comment]
@Zer0x3a 
It's obvious that python not installed on wine and it's should be installed by install.sh file so make sure you executed it rightly or try execute it's code line by line by yourself
@hostbob 
This code have been already written on kali machine and tested on it,the problem is in your machine you have surely done some mistakes in installing it's requirements on wine machine so there's no issue here !!
